package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"speedtest-tray/internal/config"
)

func main() {
	root, err := repoRoot()
	if err != nil {
		panic(err)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("export const PHASES = {\n")
	writePhase(&out, "INITIALIZING", config.PhaseInitializing)
	writePhase(&out, "GETTING_INFO", config.PhaseGettingInfo)
	writePhase(&out, "FINDING_SERVERS", config.PhaseFindingServers)
	writePhase(&out, "SELECTING_SERVER", config.PhaseSelectingServer)
	writePhase(&out, "SERVER_SELECTED", config.PhaseServerSelected)
	writePhase(&out, "PING_TEST", config.PhasePingTest)
	writePhase(&out, "STARTING_DOWNLOAD", config.PhaseStartingDownload)
	writePhase(&out, "DOWNLOADING", config.PhaseDownloading)
	writePhase(&out, "STARTING_UPLOAD", config.PhaseStartingUpload)
	writePhase(&out, "UPLOADING", config.PhaseUploading)
	writePhase(&out, "COMPLETED", config.PhaseCompleted)
	writePhase(&out, "FAILED", config.PhaseFailed)
	writePhase(&out, "STOPPED", config.PhaseStopped)
	out.WriteString("};\n\n")
	out.WriteString("export const CONFIG = {\n")
	fmt.Fprintf(&out, "  UI_HIDE_DELAY_MS: %d,\n", config.UIHideDelayMs)
	fmt.Fprintf(&out, "  GAUGE_MAX_DOWNLOAD: %d,\n", config.GaugeMaxDownload)
	fmt.Fprintf(&out, "  GAUGE_MAX_UPLOAD: %d,\n", config.GaugeMaxUpload)
	fmt.Fprintf(&out, "  APP_VERSION: %q,\n", config.AppVersion)
	out.WriteString("};\n\n")
	out.WriteString("export const ERRORS = {\n")
	fmt.Fprintf(&out, "  NO_INTERNET: %q,\n", config.ErrNoInternet)
	out.WriteString("};\n\n")
	out.WriteString("export const MESSAGES = {\n")
	fmt.Fprintf(&out, "  NO_INTERNET: %q,\n", config.MsgNoInternet)
	out.WriteString("};\n")

	targetDir := filepath.Join(root, "frontend", "src", "generated")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(filepath.Join(targetDir, "config.js"), out.Bytes(), 0644); err != nil {
		panic(err)
	}
}

func writePhase(out *bytes.Buffer, name string, phase config.Phase) {
	fmt.Fprintf(out, "  %s: %q,\n", name, string(phase))
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("cannot locate generator")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..")), nil
}
