// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {speedtest_util} from '../models';

export function ApplyRoundedCorners():Promise<void>;

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<speedtest_util.HistoryEntry>>;

export function HideWindow():Promise<void>;

export function OpenHistoryJSON():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartTest():Promise<void>;

export function StopTest():Promise<void>;

export function ToggleWindow():Promise<void>;
