// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {speedtest_util} from '../models';

export function ApplyRoundedCorners():Promise<void>;

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<speedtest_util.HistoryEntry>>;

export function GetLaunchAtLogin():Promise<boolean>;

export function GetUpdateInfo():Promise<updater.UpdateInfo>;

export function HideWindow():Promise<void>;

export function OpenHistoryJSON():Promise<void>;

export function Quit():Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function SkipUpdate(arg1:string):Promise<void>;

export function StartTest():Promise<void>;

export function StopTest():Promise<void>;

export function ToggleWindow():Promise<void>;
