// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRoundedCorners() {
  return window['go']['gui_wails']['App']['ApplyRoundedCorners']();
}

export function ClearHistory() {
  return window['go']['gui_wails']['App']['ClearHistory']();
}

export function GetHistory() {
  return window['go']['gui_wails']['App']['GetHistory']();
}

export function HideWindow() {
  return window['go']['gui_wails']['App']['HideWindow']();
}

export function OpenHistoryJSON() {
  return window['go']['gui_wails']['App']['OpenHistoryJSON']();
}

export function Quit() {
  return window['go']['gui_wails']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['gui_wails']['App']['ShowWindow']();
}

export function StartTest() {
  return window['go']['gui_wails']['App']['StartTest']();
}

export function StopTest() {
  return window['go']['gui_wails']['App']['StopTest']();
}

export function ToggleWindow() {
  return window['go']['gui_wails']['App']['ToggleWindow']();
}
