// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRoundedCorners():Promise<void>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartTest():Promise<void>;

export function StopTest():Promise<void>;

export function ToggleWindow():Promise<void>;
